Add array of objects to paint
Sacristan/godot_scene_object_brush pull request #1
Opened 2024-04-29 14:17 UTC by lluancarlo

Hey @Sacristan, I've been using your tools with this small change I did. Maybe you wanna take a look. It is really helpful though, thanks a lot!

https://github.com/Sacristan/godot_scene_object_brush/assets/32052204/7e95f0b9-e965-4700-bdd6-65f6ecf1a3d1

2024-05-03 12:48 UTC, Sacristan requested changes
@lluancarlo thanks for your work. I would implement that a bit differently. However, it works

2024-05-03 12:48 UTC, Sacristan commented on addons/scene_object_brush/Brush.gd
> +	return randf_range(0, paintableObjects.size())
do null checks

2024-05-03 12:48 UTC, Sacristan commented on addons/scene_object_brush/plugin.cfg
> -version="1.0.1"
please revert changes to this since this is not in main yet. Also this is not a patch :) Ill increment this once there's a new release

2024-05-12 08:27 UTC, Sacristan commented on addons/scene_object_brush/Brush.gd
> +	return randf_range(0, paintableObjects.size())
also this would need to use randi_range since indices are integers, not floats

2024-05-12 08:35 UTC, Sacristan commented
@lluancarlo i will resolve this in a separate pull request and will close this one once new one's merged!

2024-05-12 12:49 UTC, Sacristan commented
handled at 
https://github.com/Sacristan/godot_scene_object_brush/pull/7

2024-05-12 12:49 UTC, closed without merging

2024-05-12 12:51 UTC, lluancarlo commented
Sorry for the delay! I haven't had time for it these days. Thank you :)

2024-05-12 12:52 UTC, Sacristan commented
@lluancarlo no worries! :) thx for your input! I think i had a version of this w array of painted objects, but it was some half broken older version of this for some gamejam :D